apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb
  namespace: your-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serviceb
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
      - name: serviceb
        image: your-docker-image/serviceb:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"