version: '3.8'

services:
  api:
    build:
      context: ./src/Api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

  servicea:
    build:
      context: ./src/Services/ServiceA
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - app-network

  serviceb:
    build:
      context: ./src/Services/ServiceB
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge